server:
  port: 8083

eureka:
  #  instance:
  #    instance-id: ${spring.application.name}:${spring.application.instance_id:${random.value}}
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://k6c206.p.ssafy.io:8761/eureka
  instance:
    prefer-ip-address: true

spring:
  application:
    name: auth-server
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher
  datasource:
    url: jdbc:mysql://k6c206.p.ssafy.io:3306/advent?useSSL=false&useUnicode=true&serverTimezone=Asia/Seoul
    username: advent
    password: make123@@
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: none
      use-new-id-generator-mappings: true
    show-sql: true
  profiles:
    include:
      - oauth-prod
  jackson:
    property-naming-strategy: SNAKE_CASE
  cloud:
    discovery:
      enabled: true

logging:
  level.org.springframework: info
  level.org.springframework.web: info
  level.com.amazonaws.util.EC2MetadataUtils: error

cors:
  allowed-origins: "*"
  allowed-methods: GET,POST,PUT,DELETE,OPTIONS,PATCH
  allowed-headers: "*"
  max-age: 3600

jwt:
  secret: c2lsdmVybmluZS10ZWNoLXNwcmluZy1ib290LWp3dC10dXRvcmlhbC1zZWNyZXQtc2lsdmVybmluZS10ZWNoLXNwcmluZy1ib290LWp3dC10dXRvcmlhbC1zZWNyZXQK

app:
  auth:
    tokenSecret: 926D96C90030DD58429D2751AC1BDBBC
    tokenExpiry: 3600000
    refreshTokenExpiry: 604800000
  oauth2:
    authorizedRedirectUris:
      - https://makeourspecial.day/oauth/redirect